name: Default pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    # runs-on: ['ubuntu-latest', 'windows-latest']
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      # - run: npm run test:once

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
      - run: npm ci
      - run: npm run build

      - name: Set deployment target path
        id: deploy_target
        run: |
          echo "target_path=/var/www/jackowskiego24.pl/public_html" >> "$GITHUB_OUTPUT"

      - name: Test ssh connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: whoami

      - name: Upload files content via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: ./dist/*
          target: ${{ steps.deploy_target.outputs.target_path }}
          rm: true

      - name: Move files from dist to public_html
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ steps.deploy_target.outputs.target_path }}/dist/
            mv * ..
            rm -rf ${{ steps.deploy_target.outputs.target_path }}/dist/
